clubmanager/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.defaults import *
from manager.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# Init dajax
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clubmanager.views.home', name='home'),
    # url(r'^clubmanager/', include('clubmanager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),    
    (r'^$', 'manager.views.main_menu'),
    
    (r'^reports/$', 'manager.views.reports_menu'),
    (r'^reports/(?P<type>\w+)/allmembers/$', 'manager.views.list_flight_years_allmembers'),
    (r'^reports/(?P<type>\w+)/allmembers/(?P<year>\d+)/$', 'manager.views.report_members_yearly'),
    
    (r'^reports/(?P<type>\w+)/bytype/$', 'manager.views.list_flight_years_bytype'),
    (r'^reports/(?P<type>\w+)/bytype/(?P<year>\d+)/$', 'manager.views.report_bytype_yearly'),
    
    (r'^reports/(?P<type>\w+)/detailed/$', 'manager.views.report_detailed'),

    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Login / logout.
    (r'^login/$', 
     'django.contrib.auth.views.login', 
     {'template_name': 'accounts/login.html'}),
    
    (r'^logout/$', 'manager.views.logout_page'),
    
    (r'^password_change/$', 
     'django.contrib.auth.views.password_change', 
     {'template_name': 'accounts/password_change_form.html'}),

    (r'^password_change/done/$', 
     'django.contrib.auth.views.password_change_done', 
     {'template_name': 'accounts/password_change_done.html'}),

    (r'^password_reset/$', 
     'django.contrib.auth.views.password_reset', 
     {'template_name': 'accounts/password_reset_form.html',
      'email_template_name': 'accounts/password_reset_email.html'}),

    (r'^password_reset/done/$', 
     'django.contrib.auth.views.password_reset_done', 
     {'template_name': 'accounts/password_reset_done.html'}),

    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
     'django.contrib.auth.views.password_reset_confirm', 
     {'template_name': 'accounts/password_reset_confirm.html'}),

    (r'^reset/done/$', 
     'django.contrib.auth.views.password_reset_complete', 
     {'template_name': 'accounts/password_reset_complete.html'}),

    (r'^signup/$', 
     'manager.views.signup', 
     {'template_name': 'accounts/signup_form.html',
      'email_template_name': 'accounts/signup_email.html'}),

    (r'^signup/done/$', 
     'manager.views.signup_done', 
     {'template_name': 'accounts/signup_done.html'}),

    (r'^signup/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
     'manager.views.signup_confirm'),

    (r'^signup/complete/$', 
     'manager.views.signup_complete', 
     {'template_name': 'accounts/signup_complete.html'}),
                        
    url (
       regex = '^aircraft/list/$',
       view =  AircraftListView.as_view(),
       name = 'aircraft_list'
     ),

    url (
        regex = '^aircraft/create/$',
        view =  AircraftCreateView.as_view(),
        name = 'aircraft_create'
    ),

    url (
        regex = '^aircraft/detail/(?P<pk>\d+)/$',
        view =  AircraftDetailView.as_view(),
        name = 'aircraft_detail'
    ),
    
    url (
        regex = '^aircraft/delete/(?P<pk>\d+)/$',
        view =  AircraftDeleteView.as_view(),
        name = 'aircraft_delete'
    ),
    
    url (
        regex = '^aircraft/update/(?P<pk>\d+)/$',
        view =  AircraftUpdateView.as_view(),
        name = 'aircraft_update'
    ),

    url (
       regex = '^purpose/list/$',
       view =  PurposeListView.as_view(),
       name = 'purpose_list'
     ),

    url (
        regex = '^purpose/create/$',
        view =  PurposeCreateView.as_view(),
        name = 'purpose_create'
    ),

    url (
        regex = '^purpose/detail/(?P<pk>\d+)/$',
        view =  PurposeDetailView.as_view(),
        name = 'purpose_detail'
    ),
    
    url (
        regex = '^purpose/delete/(?P<pk>\d+)/$',
        view =  PurposeDeleteView.as_view(),
        name = 'purpose_delete'
    ),
    
    url (
        regex = '^purpose/update/(?P<pk>\d+)/$',
        view =  PurposeUpdateView.as_view(),
        name = 'purpose_update'
    ),
    
    url (
       regex = '^member/list/$',
       view =  MemberListView.as_view(),
       name = 'member_list'
     ),

    url (
        regex = '^member/create/$',
        view =  MemberCreateView.as_view(),
        name = 'member_create'
    ),

    url (
        regex = '^member/detail/(?P<pk>\d+)/$',
        view =  MemberDetailView.as_view(),
        name = 'member_detail'
    ),
    
    url (
        regex = '^member/delete/(?P<pk>\d+)/$',
        view =  MemberDeleteView.as_view(),
        name = 'member_delete'
    ),
    
    url (
        regex = '^member/update/(?P<pk>\d+)/$',
        view =  MemberUpdateView.as_view(),
        name = 'member_update'
    ),
    
    url (
       regex = '^logbook/(?P<type>\w+)/list/$',
       view =  LogbookListView.as_view(),
       name = 'logbook_list'
     ),

    url (
        regex = '^logbook/(?P<type>\w+)/create/$',
        view =  LogbookCreateView.as_view(),
        name = 'logbook_create'
    ),

    url (
        regex = '^logbook/(?P<type>\w+)/detail/(?P<pk>\d+)/$',
        view =  LogbookDetailView.as_view(),
        name = 'logbook_detail'
    ),
    
    url (
        regex = '^logbook/delete/(?P<pk>\d+)/$',
        view =  LogbookDeleteView.as_view(),
        name = 'logbook_delete'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/update/(?P<pk>\d+)/$',
        view =  LogbookUpdateView.as_view(),
        name = 'logbook_update'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/$',
        view =  LogbookManageView.as_view(),
        name = 'logbook_manage'
    ),

    url (
        regex = '^logbook/(?P<type>\w+)/manage/advanced/(?P<logbook_id>\d+)/$',
        view =  LogbookManageAdvancedView.as_view(),
        name = 'logbook_manage_advanced'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/create/flight/$',
        view =  FlightCreateView.as_view(),
        name = 'flight_create'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/create/flight/advanced/$',
        view =  AdvancedFlightCreateView.as_view(),
        name = 'flight_create_advanced'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/edit/flight/(?P<pk>\d+)/$',
        view =  FlightUpdateView.as_view(),
        name = 'flight_create'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/edit/flight/advanced/(?P<pk>\d+)/$',
        view =  AdvancedFlightUpdateView.as_view(),
        name = 'flight_update_advanced'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/delete/flight/(?P<pk>\d+)/$',
        view =  FlightDeleteView.as_view(),
        name = 'flight_delete'
    ),
    
    url (
        regex = '^logbook/(?P<type>\w+)/manage/(?P<logbook_id>\d+)/delete/flight/advanced/(?P<pk>\d+)/$',
        view =  AdvancedFlightDeleteView.as_view(),
        name = 'flight_delete_advanced'
    ),
    
    url (
        regex = '^organisation/create/$',
        view =  OrganisationCreateView.as_view(),
        name = 'organisation_create'
    ),

    url (
        regex = '^organisation/update/(?P<pk>\d+)/$',
        view =  OrganisationUpdateView.as_view(),
        name = 'organisation_update'
    ),
    
    url (
        regex = '^document/create/(?P<member_id>\d+)/$',
        view =  DocumentCreateView.as_view(),
        name = 'document_create'
    ),

    url (
        regex = '^document/update/(?P<member_id>\d+)/(?P<pk>\d+)/$',
        view =  DocumentUpdateView.as_view(),
        name = 'document_update'
    ),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

manager/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import timedelta, date
from django.contrib.auth.models import User
from django.db.models.signals import post_save


AIRCRAFT_TYPE =(
('sailplane', _('Sailplane')),
('powered', _('Powered Aircraft')),
)

BILLING_TYPE =(
('noncommercial', _('Non-commerical')),
('commercial', _('Commercial')),
)

DOCUMENT_TYPE =(
('medical', _('Medical')),
('gpl', _('Glider pilot license')),
('ppl', _('Private pilot license')),
)

OWNERSHIP_TYPE =(
('private', _('Private ownership')),
('club', _('Club ownership')),
)

GENDER =(
('m', _('Male')),
('f', _('Female')),
)

# ClubManager model

class Organisation(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    website = models.CharField(_("Website"), max_length=128, blank=True, null=True)
    email = models.EmailField(_("Email"), max_length=128, blank=True, null=True)
    address = models.CharField(_("Address"), max_length=128)
    city = models.CharField(_("City"), max_length=128)
    zip = models.CharField(_("ZIP"), max_length=16)
    country = models.CharField(_("Country"), max_length=64)
    vatid = models.CharField(_("VAT ID"), max_length=32)
    phone1 = models.CharField(_("Phone 1"), max_length=64)
    phone2 = models.CharField(_("Phone 2"), max_length=64, blank=True, null=True)
    fax = models.CharField(_("Fax"), max_length=64, blank=True, null=True)
    administrator = models.OneToOneField(User)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _("Organisation")
        verbose_name_plural = _("Organisations")

class Member(models.Model):
   user = models.OneToOneField(User, null=True) 
   first_name = models.CharField(_("First name"), max_length=64)
   last_name = models.CharField(_("Last name"), max_length=64)
   email = models.CharField(_("Email"), max_length=64, blank=True, null=True)
   birthday = models.DateField(_("Birthday"), blank=True, null=True)
   gender = models.CharField(_("Gender"), max_length=1, choices = GENDER, blank=True, null=True)
   address = models.CharField(_("Address"), max_length=128, blank=True, null=True)
   city = models.CharField(_("City"), max_length=128, blank=True, null=True)
   zip = models.CharField(_("ZIP"), max_length=16, blank=True, null=True)
   country = models.CharField(_("Country"), max_length=64, blank=True, null=True)
   vatid = models.CharField(_("VAT ID"), max_length=32, blank=True, null=True)
   phone_mobile = models.CharField(_("Mobile Phone"), max_length=64, blank=True, null=True)
   phone_home = models.CharField(_("Home Phone"), max_length=64, blank=True, null=True)
   phone_work = models.CharField(_("Work Phone"), max_length=64, blank=True, null=True)
   fax = models.CharField(_("Fax"), max_length=64, blank=True, null=True)
   organisation = models.ForeignKey(Organisation)
   picture = models.ImageField(_("Picture"), upload_to="member_images/", blank=True, null=True)
   external_id = models.CharField(_("External Id"), max_length=16, blank=True, null=True)

   date_joined = models.DateTimeField(_("Date joined"), default=datetime.datetime.now)
   last_login = models.DateTimeField(_("Last login"), default=datetime.datetime.now)
   last_password_check = models.DateTimeField(_("Last password check"), default=datetime.datetime.now)

   def __unicode__(self):
      return u'%s %s, %s' % (self.first_name, self.last_name, self.city)

   class Meta:
      verbose_name = _("Member")
      verbose_name_plural = _("Members")        

class Document(models.Model):
   type = models.CharField(_("Type"), max_length=20, choices = DOCUMENT_TYPE)
   number = models.CharField(_("Document Number"), max_length=64, blank=True, null=True)
   date_of_issue = models.DateField(_("Date of issue"), blank=True, null=True)
   valid_until = models.DateField(_("Valid until"), blank=True, null=True)
   document_class = models.CharField(_("Class"), max_length=32, blank=True, null=True)
   remark = models.CharField(_("Remark"), max_length=256, blank=True, null=True)
   member = models.ForeignKey(Member)       
      
   def __unicode__(self):
      return u'%s %s %s %s %s' % (self.member.last_name, self.member.first_name, self.type, self.valid_until, self.remark)
    
   class Meta:
     verbose_name = _("Document")
     verbose_name_plural = _("Documents")
     
class Aircraft(models.Model):
   type = models.CharField(_("Type"), max_length=20, choices = AIRCRAFT_TYPE)
   ownership = models.CharField(_("Ownership"), max_length=20, choices = OWNERSHIP_TYPE)
   make = models.CharField(_("Make"), max_length=64)
   model = models.CharField(_("Model"), max_length=64)
   serial_number = models.CharField(_("Serial number"), max_length=64)
   registration = models.CharField(_("Registration"), max_length=16)
   competition_number = models.CharField(_("Competition number"), max_length=4, blank=True, null=True)
   external_id = models.CharField(_("External Id"), max_length=16, blank=True, null=True)
   organisation = models.ForeignKey(Organisation)       
      
   def __unicode__(self):
      return u'%s, %s (%s)' % (self.model, self.registration, self.competition_number)
    
   class Meta:
     verbose_name = _("Airplane")
     verbose_name_plural = _("Airplanes")
     
class Purpose(models.Model):
   type = models.CharField(_("Type"), max_length=20, choices = AIRCRAFT_TYPE)
   name = models.CharField(_("Name"), max_length=64)
   billing_type = models.CharField(_("Billing type"), max_length=20, choices = BILLING_TYPE)
   organisation = models.ForeignKey(Organisation)       
      
   def __unicode__(self):
      return u'%s' % (self.name)
    
   class Meta:
     verbose_name = _("Purpose")
     verbose_name_plural = _("Purposes")
     
   
class Logbook(models.Model):
   type = models.CharField(_("Type"), max_length=20, choices = AIRCRAFT_TYPE)
   date = models.DateField(_("Date"), blank=True, null=True)
   organisation = models.ForeignKey(Organisation)       
      
   def __unicode__(self):
      return u'%s | %s, %s' % (self.date, self.type, self.organisation.name)
    
   class Meta:
     verbose_name = _("Logbook")
     verbose_name_plural = _("Logbooks")
     unique_together = ('type', 'date',)     
   
class Flight(models.Model):
   date = models.DateField(_("Date"), default=datetime.date.today)
   organisation = models.ForeignKey(Organisation)
   pilot = models.ForeignKey(Member, related_name='pilot_flights')
   instructor = models.ForeignKey(Member, blank=True, null=True, related_name='instructor_flights')
   aircraft = models.ForeignKey(Aircraft)
   purpose = models.ForeignKey(Purpose)
   first_name = models.CharField(_("First name"), max_length=128, blank=True, null=True)
   last_name = models.CharField(_("Last name"), max_length=128, blank=True, null=True)
   instructor_first_name = models.CharField(_("Instructor first name"), max_length=128, blank=True, null=True)
   instructor_last_name = models.CharField(_("Instructor last name"), max_length=128, blank=True, null=True)
   make = models.CharField(_("Make"), max_length=64, blank=True, null=True)
   model = models.CharField(_("Model"), max_length=64, blank=True, null=True)
   serial_number = models.CharField(_("Serial number"), max_length=64, blank=True, null=True)
   registration = models.CharField(_("Registration"), max_length=16, blank=True, null=True)
   time_block_off = models.TimeField(_("Block off"), blank=True, null=True)
   time_takeoff = models.TimeField(_("Takeoff"), blank=True, null=True)
   time_tow_release = models.TimeField(_("Tow release"), blank=True, null=True)
   time_landing = models.TimeField(_("Landing"), blank=True, null=True)
   time_block_on = models.TimeField(_("Block off"), blank=True, null=True)
   flight_time = models.TimeField(_("Flight time"), blank=True, null=True)
   remark = models.CharField(_("Remark"), max_length=1024, blank=True, null=True)
   igc_file = models.FileField(_("IGC file"), upload_to="igc/", blank=True, null=True)
   logbook = models.ForeignKey(Logbook)
   
   def __unicode__(self):
      return u'%s %s %s %s %s %s %s' % (self.date, self.organisation.name, self.first_name, self.last_name, self.make, self.model, self.registration)
      
   def total_airborne_time(self):
      if not self.time_takeoff:
         return '0:0';
      if not self.time_landing:
         return '0:0';
         
      delta_time = self.time_landing - self.time_takeoff
      
      print delta_time
      
      hours = delta_time.seconds / 60 / 60 
      minutes = delta_time.seconds / 60
      return '%s:%s' % (hours, minutes)
      
   def __init__(self, *args, **kwargs):
      super(Flight, self).__init__(*args, **kwargs)
      if self.time_landing and self.time_takeoff:
         self.flight_time = (datetime.datetime.min + (datetime.datetime.combine(date.today(), self.time_landing) - datetime.datetime.combine(date.today(), self.time_takeoff))).time()

   def save(self, *args, **kwargs):
      if self.time_landing and self.time_takeoff:
         self.flight_time = (datetime.datetime.min + (datetime.datetime.combine(date.today(), self.time_landing) - datetime.datetime.combine(date.today(), self.time_takeoff))).time()
      if self.logbook:
         self.date = self.logbook.date
      super(Flight, self).save(*args, **kwargs)      
    
   class Meta:
     verbose_name = _("Flight")
     verbose_name_plural = _("Flights")
   

templates/manager/display_pdf.html
{% extends "index.html" %}{% block content %}
{% load i18n %}
    <h1>&nbsp;</h1>
    <h2>{% trans "PDF converted to HTML" %}</h2>
    {{ pdf_to_html }}
{% endblock %}

templates/manager/document_form.html
{% extends "index.html" %}{% block content %}
{% load i18n %}
    <h2>{% trans "Document" %}</h2>
    <h1>&nbsp;</h1>

<form action="." method="POST">{% csrf_token %}
   {% include "base_form.html" %}
   <label for="submit"></label>
   <input type="submit" id="submit" class="button white" value="{% trans 'Save' %}" />
</form>

{% endblock %}

templates/manager/entry_create.html
{% extends "index.html" %}{% block content %}
{% load i18n %}

<form action="." method="POST">{% csrf_token %}
   {% include "base_form.html" %}
   <label for="submit"></label>
   <input type="submit" id="submit" class="button white" value="{% trans 'Save' %}" />
</form>

{% endblock %}

templates/manager/file_upload.html
{% extends "index.html" %}{% block content %}
{% load i18n %}

<form enctype="multipart/form-data" action="." method="POST">{% csrf_token %}
   {% include "base_form.html" %}
   <label for="submit"></label>
   <input type="submit" id="submit" class="button white" value="{% trans 'Upload it' %}" />
</form>

{% endblock %}

templates/manager/flight_confirm_delete.html
{% extends "index.html" %}{% block content %}
{% load i18n %}

    <h1>&nbsp;</h1>
    <h2>{% trans "Delete flight ?" %}</h2>
    
   <form action="." method="POST">{% csrf_token %}
      <input type="submit" id="submit" class="button white" value="{% trans 'Yes, delete !' %}" />
   </form>
     
{% endblock %}

templates/manager/listing_create.html
{% extends "index.html" %}{% block content %}
{% load i18n %}

<form action="." method="POST">{% csrf_token %}
   {% include "base_form.html" %}
   <label for="submit"></label>
   <input type="submit" id="submit" class="button white" value="{% trans 'Save' %}" />
</form>

{% endblock %}

templates/manager/logbook_manage.html
{% extends "index.html" %}
{% block content %}
{% load i18n %}
       <h2>{% trans "Manage logbook" %}</h2>
       <h1>&nbsp;</h1>

   <form action="/logbook/{{ type }}/manage/{{ logbook.pk }}/create/flight/" method="POST">{% csrf_token %}

        <div class="ui-widget">
            <input id="id_pilot" name="pilot" type="hidden">   
            <input id="pilot_ajax" name="pilot_ajax" type="text" placeholder="{% trans 'Pilot' %}" onkeyup="searchPilot();" autofocus required>   
            <input id="id_aircraft" name="aircraft" type="hidden">   
            <input id="aircraft_ajax" name="aircraft_ajax" type="text" placeholder="{% trans 'Aircraft' %}" onkeyup="searchAircraft();" required>
            <input type="submit" id="inlinesubmit" class="button white" value="{% trans 'Add' %}" />
        </div>

   </form>

   <br/>
    <h2>{% trans "Flights" %} - {{ type }} </h2><a href="/logbook/{{ type }}/manage/{{ logbook.pk }}/create/flight/" class="btna btnrf" title="{% trans 'Add new flight' %}">&nbsp;</a>
    <fieldset>
        <table>

            <thead>
            <tr>
                <th>ID</th>
                <th>{% trans "Pilot" %}</th>
                <th>{% trans "Instructor" %}</th>
                <th>{% trans "Aircraft" %}</th>
                {% ifequal type "powered" %}
                <th>{% trans "Block off" %}</th>
                {% endifequal %}
                <th>{% trans "Takeoff" %}</th>
                <th>{% trans "Release" %}</th>
                <th>{% trans "Landing" %}</th>
                {% ifequal type "powered" %}
                <th>{% trans "Block on" %}</th>
                {% endifequal %}
                <th class="ths">&nbsp;</th>
                <th class="ths">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
{% for object in flights %}
            <tr>
               <td>{{ object.pk }}</td>
               <td>{{ object.first_name }} {{ object.last_name }}</td>
               <td>{{ object.instructor_first_name }} {{ object.instructor_last_name }}</td>
               <td>{{ object.model }} ({{ object.registration }})</td>
               {% ifequal type "powered" %}
               <td id="time_block_off-{{ object.pk }}">{% if object.time_block_off %}{{ object.time_block_off|date:'H:i' }}{% else %}<a class="button white" href="#" onclick="setFlightEventTime({{ object.pk }}, 'time_block_off');">Now</a>{% endif%}</td>
               {% endifequal %}
               <td id="time_takeoff-{{ object.pk }}">{% if object.time_takeoff %}{{ object.time_takeoff|date:'H:i' }}{% else %}<a class="button white" href="#" onclick="setFlightEventTime({{ object.pk }}, 'time_takeoff');">Now</a>{% endif%}</td>
               <td id="time_tow_release-{{ object.pk }}">{% if object.time_tow_release %}{{ object.time_tow_release|date:'H:i' }}{% else %}<a class="button white" href="#" onclick="setFlightEventTime({{ object.pk }}, 'time_tow_release');">Now</a>{% endif%}</td>
               <td id="time_landing-{{ object.pk }}">{% if object.time_landing %}{{ object.time_landing|date:'H:i' }}{% else %}<a class="button white" href="#" onclick="setFlightEventTime({{ object.pk }}, 'time_landing');">Now</a>{% endif%}</td>
               {% ifequal type "powered" %}
               <td id="time_block_on-{{ object.pk }}">{% if object.time_block_on %}{{ object.time_block_on|date:'H:i' }}{% else %}<a class="button white" href="#" onclick="setFlightEventTime({{ object.pk }}, 'time_block_on');">Now</a>{% endif%}</td>
               {% endifequal %}
               <td class="tds"><a href="/logbook/{{ type }}/manage/{{ logbook.pk }}/edit/flight/{{ object.pk }}/" class="btne" title="{% trans 'Edit' %}">&nbsp;</a></td>
               <td class="tds"><a href="/logbook/{{ type }}/manage/{{ logbook.pk }}/delete/flight/{{ object.pk }}/" class="btnd" title="{% trans 'Delete' %}">&nbsp;</a></td>
            </tr>
{% endfor %}
            </tbody>
            <tfoot>

            <tr>
                <td colspan="10"></td>
            </tr>
            </tfoot>
        </table>
    </fieldset>

{% endblock %}
{% block scripts %}
<script type="text/javascript">
   
   Number.prototype.pad = function(size){
      if(typeof(size) !== "number"){size = 2;}
      var s = String(this);
      while (s.length < size) s = "0" + s;
      return s;
    }
    
   function searchPilot() 
   {
      var search = $('#pilot_ajax').val()
      Dajaxice.manager.get_pilot(pilotCallback, {'search_data': search});
   }
    
   function pilotCallback(data) 
   {
      $( "#pilot_ajax" ).autocomplete({source: data, delay: 500,
         select: function(event, ui) {
            var selectedObj = ui.item;
            $('#id_pilot').val(selectedObj.id);
            return true;
		}});
   }

   function searchAircraft() 
   {
      var search = $('#aircraft_ajax').val()
      Dajaxice.manager.get_aircraft(aircraftCallback, {'search_data': search, 'type': '{{ type }}'});
   }
    
   function aircraftCallback(data) 
   {
      $( "#aircraft_ajax" ).autocomplete({source: data, delay: 500, 
         select: function(event, ui) {
            var selectedObj = ui.item;
            $('#id_aircraft').val(selectedObj.id);
            return true;
		}});
   }
   
   function setFlightEventTime(flight_id, event_name)
   {
      var date = new Date();
      var minutes = date.getMinutes();
      var hour = date.getHours();
      var timeString = hour.pad() + ":" + minutes.pad();
      Dajaxice.manager.set_flight_event_time(flightEventTimeCallback, {'flight_id': flight_id, 'event_name': event_name, 'time': timeString});
   }

   function flightEventTimeCallback(data)
   {
      $( "#"+data.event_name+"-"+data.flight_id ).children().replaceWith(function(){ return data.time; });
   }
</script>
{% endblock %}

templates/manager/purpose_list.html
{% extends "index.html" %}{% block content %}
{% load i18n %}

    <h1>&nbsp;</h1>
    <h2>{% trans "Flight purposes" %}</h2><a href="/purpose/create/" class="btna btnrf" title="{% trans 'Add new purpose' %}">&nbsp;</a>
    <fieldset>
        <table id="sortedTable" class="tablesorter">

            <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Type" %}</th>
                <th>{% trans "Billing type" %}</th>
                <th class="ths">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
{% for object in object_list %}
            <tr>
               <td><a href="/purpose/update/{{ object.pk }}/">{{ object.name }}</a></td>
               <td><a href="/purpose/update/{{ object.pk }}/">{{ object.get_type_display }}</a></td>
               <td><a href="/purpose/update/{{ object.pk }}/">{{ object.get_billing_type_display }}</a></td>
               <td class="tds"><a href="/purpose/update/{{ object.pk }}/" class="btne" title="{% trans 'Edit' %}">&nbsp;</a></td>
            </tr>
{% endfor %}
            </tbody>
            <tfoot>

            <tr>
                <td colspan="10"></td>
            </tr>
            </tfoot>
        </table>
    </fieldset>

{% endblock %}